# Generated by Django 6.0.3 on 2026-05-12 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da peça')),
                ('color', models.CharField(max_length=100, verbose_name='Cor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('image_key', models.CharField(blank=True, help_text='Nome/caminho da imagem no bucket', max_length=255, null=True, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Item de Uniforme',
                'verbose_name_plural': 'Itens de Uniforme',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniformOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_orders', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Pedido de Uniforme',
                'verbose_name_plural': 'Pedidos de Uniforme',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniformOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=4, verbose_name='Tamanho')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.uniformorder', verbose_name='Pedido')),
                ('uniform_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.uniformitem', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
