# Generated by Django 6.0.3 on 2026-05-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_alunos_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformitem',
            name='item_type',
            field=models.CharField(choices=[('camiseta', 'Camiseta'), ('moletom', 'Moletom'), ('outro', 'Outro')], default='camiseta', max_length=20, verbose_name='Tipo'),
        ),
    ]
