# Generated by Django 6.0.3 on 2026-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_uniformitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformorder',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('preparando', 'Em Preparação'), ('disponivel', 'Disponível para Retirada'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
