# Generated by Django 6.0.3 on 2026-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_uniformorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='image_key',
        ),
        migrations.RemoveField(
            model_name='uniformitem',
            name='image_key',
        ),
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feeds/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='uniformitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uniforms/', verbose_name='Imagem'),
        ),
    ]
